config/routes.rb
ControllerExercise::Application.routes.draw do

  resources :users, :products

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name, :price
  validates :name, :uniqueness => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :products
  attr_accessible :job_title, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.includes(:user).all
    respond_to do |format|
      format.html # show default view
      format.json {render :json => @products}
    end
  end

  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { render :action => "create" }
        format.json { render :json => @product }
      else
        format.html { render :action => "new" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.where(:id => params[:id]).first
  end

  def edit
    @product = Product.where(:id => params[:id]).first
  end

  def update
    @product = Product.where(:id => params[:id]).first

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, :notice => 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = Product.where(:id => params[:id]).first
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_dropdown.html.erb
<ul class="nav">
  <li class="dropdown">
    <a href="#"
          class="dropdown-toggle"
          data-toggle="dropdown">
          New
          <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to 'New User', new_user_path %></li>
      <li><%= link_to 'New Product', new_product_path %></li>
    </ul>
  </li>
</ul>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://schneems.com/">Rails Tutorial</a>
    by Richard Schneeman
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", 'https://twitter.com/DearDonald' %></li>
      <li><a href="https://github.com/ddmck">Customised by Donald McKendrick</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class='navbar navbar-fixed-top navbar-inverse'>
  <div class="navbar-inner">
    <div class="container-fluid">
      <%= link_to "Schneems 5" , "http://schneems.com/post/27122707453/databases-rails-week-5-controllers", id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= render "layouts/dropdown" %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Products", products_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ControllerExercise</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %> 
</head>
<body>

<%= render 'layouts/header' %>


<% if flash[:notice].present? %>
  <p class="flash-notice"><%= flash[:notice] %></p>
<% end %>

<div class="container-fluid">
<%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/products/_form.html.erb
<div class="span4 offset1">
<%= form_for(@product) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
</div>

app/views/products/create.html.erb
<h2>Product Created Successfully<h2>

<%= @product.name %> added to the website, it costs: $<%= @product.price %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1> Products in the market </h2>

<div class="row-fluid"><div class="span2 offset2"><%= link_to 'New Product', new_product_path, class: "btn btn-primary" %></div></div>
<p></p>
<div class="row-fluid">
<div class="span8 offset2">
<table class="table table-bordered table-striped table-condensed">
  <thead>
    <tr>
      <th>Product name</th>
      <th>Price</th>
      <th>Sold by</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td>$<%= product.price %></td>
	  <td><%= product.user.name if product.user.present? %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
</div>
</div>

  

app/views/products/new.html.erb
<div class="row">
<div class="span2 offset1">
<h2>New Product</h2>
</div>
</div>

<%= render :partial => 'form' %>

app/views/products/show.html.erb
<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<%= link_to 'Destroy', @product, class: "btn btn-danger" , :method => :delete, :data => { :confirm => 'Are you sure?' } %>

app/views/users/_form.html.erb
<div class="span4 offset1">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :job_title %>
    <%= f.text_field :job_title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<div class="row-fluid"><div class="span2 offset2"><%= link_to 'New User', new_user_path, class: "btn btn-primary" %></div></div>
<p></p>
<div class="row-fluid">
<div class="span8 offset2">
<table class="table table-bordered table-striped table-condensed">
  <thead>
  <tr>
    <th>Name</th>
    <th>Job title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.job_title %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
</div>
</div>

app/views/users/new.html.erb
<div class="row">
<div class="span2 offset1">
<h2>New user</h2>
</div>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Job title:</b>
  <%= @user.job_title %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>